Feature/integ specs views
Benawi/Blog-App pull request #8
Opened 2023-09-13 20:52 UTC by Benawi

## [Implemented Features](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/intergration_spec_and_n_1_project.md)
### General requirements
- Make sure that there are [no linter errors](https://github.com/microverseinc/linters-config).
- Make sure that you used the correct [Gitflow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md).
- Make sure that you documented your work [in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md).
### Ruby requirements
- Follow our list of [best practices for Ruby](https://github.com/microverseinc/curriculum-ruby/blob/main/articles/ruby_best_practices.md).
### Project requirements
- [x] Make sure that the N+1 problem is solved when fetching all posts and their comments for a user.
 
   - include the screenshots of your app's logs before and after the fix
   - before
        ![before](https://github.com/Benawi/Blog-App/assets/21217148/cd87f5a9-c044-45c0-a7ae-e122746aa08d)

    - after
      ![after](https://github.com/Benawi/Blog-App/assets/21217148/8df686ba-6c90-4219-af82-97bd42706187)
-[x]  Integration specs
      -  Use Capybara to write integration tests for each view in your project.
![test resu](https://github.com/Benawi/Blog-App/assets/21217148/596bf9da-5c96-4baa-8a6c-b2beb3ebf25a)

2023-09-13 23:35 UTC, t-yanick requested changes
# STATUS: CHANGES REQUIRED

Hi @Benawi , 

### Good job so far!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Collaborative work 👍 Commits from both team members
:heavy_check_mark: Screenshots of N + 1 solution attached to PR description
:heavy_check_mark: Has Capybara gem in `Gemfile` for integration test
:heavy_check_mark: Most test cases added

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-13 23:35 UTC, t-yanick commented on spec/feature/posts_index_spec.rb
> -
- [ ] Great job working on this milestone. You are currently missing the test that `redirects to the post's show page when you click on a post.`

2023-09-13 23:35 UTC, t-yanick commented on spec/feature/posts_index_spec.rb
> -      expect(page).to have_content(post.title)
- [ ] You are currently missing:
- Test that asserts you can see the number of posts the user has written.
- Test that asserts you can see a post's title.
- Test that asserts you can see some of the post's body.
Kindly add the missing tests

2023-09-13 23:35 UTC, t-yanick commented on spec/feature/posts_index_spec.rb
> -  it 'displays user profile information' do
- [ ] You are currently missing the following tests:
- Test that asserts you can see the user's profile picture.
- Test that asserts you can see the user's username.
Kindly add these missing test cases

2023-09-13 23:35 UTC, t-yanick commented on spec/feature/posts_show_spec.rb
>      Post.create(
- [ ]  At the moment you are missing the test that asserts that you can see who wrote the post. Kindly add it.

2023-09-13 23:35 UTC, t-yanick commented on spec/feature/users_index_spec.rb
> -  it 'displays the number of posts each user has written' do
- [ ] You are currently missing the following test:
- Test that asserts you can see the number of posts each user has written.
Kindly add the missing test case

2023-09-14 06:44 UTC, Benawi commented
### Changes 
- [x] Add test cases for redirects to the post's show page when you click on a post 
- [x] Issues(already written before)fixed related to 
       - Test that asserts you can see the number of posts the user has written.
       - Test that asserts you can see a post's title.
       - Test that asserts you can see some of the post's body
       - Test that asserts that you can see who wrote the post.
       - Test that asserts you can see the number of posts each user has written.

![image](https://github.com/Benawi/Blog-App/assets/21217148/51d8e81d-2dbe-4fcb-b320-1e1fb9a1b22f)
![image](https://github.com/Benawi/Blog-App/assets/21217148/dc821bed-a1c5-4616-bc8f-def4b591e43d)

2023-09-14 07:28 UTC, tufoinnkuo10 approved these changes
## Status: Approved :heavy_check_mark:

Hi @Benawi 

Your project is complete! Great job for making the requested changes🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
✔️Descriptive Pull Request
✔️ Screenshots of N + 1 solution attached to PR description
✔️ Has Capybara gem in Gemfile for integration test
✔️ test cases added
✔️No linter errors

<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-14 08:33 UTC, merged